[workspace]
resolver = "2"
members = ["crates/ironwood", "crates/yggdrasil", "crates/ygg_stream"]

[profile.release]
opt-level = 2       # Optimize for speed
lto = true          # Link-time optimization
codegen-units = 1   # Better optimization, slower compile
strip = true        # Strip symbols
